In [1]:
#creating 3-D array with 2-D arrays
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[1,2,3]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [2]:
import numpy as np
arr=np.array([2])
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
import numpy as np
a=np.array(42)
b=np.array([[2,4],[3,5]])
c=np.array([[[2,4],[3,5],[3,6]]])
d=np.array([2,4])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
2
3
1


In [4]:
import numpy as np
arr=np.array([1,2,3,4], ndmin=6)
print(arr)
print('Number of Dimensions :', arr.ndim)


[[[[[[1 2 3 4]]]]]]
Number of Dimensions : 6


In [5]:
import numpy as np
arr=np.array([1,2,3,4])
print('Sum of arrays:')
print(arr[2]+arr[0])
print(arr[2]-arr[0])
print(arr[2]*arr[0])
print(arr[2]//arr[0])
print(arr[2]/arr[0])
print(arr[2]%arr[0])


Sum of arrays:
4
2
3
3
3.0
0


In [6]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print('2nd element on 1st row: ', arr[0,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2


In [7]:
import numpy as np
arr_1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr_1)
print('Last element from 2nd dim',arr[1,4])



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim 10


In [8]:
import numpy as np
arr_1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr_1)
print('Last element from 2nd dim',arr[1,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim 10


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:3])

[1 2 3]


In [10]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [11]:
#slice from the index 3 from end to index 1
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [12]:
# Return every other elemnt from index 1 to index 5
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:3])

[2 5]


In [13]:
#from the second elemennt, slice elemnts from index 1 to index 4

import numpy as np 
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

[7 8 9]


In [14]:
# get the data type of an array object

import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.dtype)
print(type(arr))

int32
<class 'numpy.ndarray'>


In [15]:
list=[1,2,3,4,5]
print(type(list))

<class 'list'>


In [16]:
#Get the ata type of an array containing strings

import numpy as np
arr=np.array(['apple','banana','cucumberr'])
print(arr.dtype)
#printing the highest lettered word

<U9


In [17]:
#creating an array with data type string

import numpy as np
arr=np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [18]:
# changing data type from float to integer by using 'i'
import numpy as np
arr=np.array([1.2,2.2,3.3])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [19]:
import numpy as np
arr=np.array([1,0,3,0,-1,4,0,-1])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True False  True  True False  True]
bool


In [20]:
# print the shape of 2-D array
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
#rows and columns present in the 2-D array

(2, 4)


In [21]:
# convert the 1-D array with 12 elements to 3-D array
# The outermost dimensions has 2 arrays that contains 3 arrays in it

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [22]:
# convert the 1-D array with 12 elements to 3-D array
# The outermost dimensions has 2 arrays that contains 3 arrays in it

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(3,2,2)
print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [23]:
#iterate on the elements of the following 1-D array

import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [24]:
# join 2 arrays
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [25]:
# split the array in 3 parts
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
newarr=np.array_split(arr,2)
print(newarr)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11])]


In [26]:
# find the indexes where the value is 4

import numpy as np
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [27]:
#sort the array
import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [28]:
#sort the array in decsending order
import numpy as np
arr=np.array([3,2,0,1])
newarr=np.sort(arr)[::-1]
print(newarr)

[3 2 1 0]


In [29]:
print('Hello World')

Hello World


In [30]:
print(42)

42
